apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: gitopscli-pipeline
  namespace: gitopscli-pipeline
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: build-and-push
  resources:
  - name: repo
    resourceRef:
      name: gitopscli-gitrepo
  - name: image
    resourceRef:
      name: gitopscli-imagerepo
