apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitopscli-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - binding:
        name: gitopscli-pipelinebinding
      template:
        name: gitopscli-triggertemplate